"""Smoke test the MCP endpoint using the official `mcp` Python client.

Verifies that:
  1. /mcp responds to streamable-HTTP initialize handshake
  2. tools/list returns one entry per FastAPI route
  3. tools/call on a read endpoint (features_list) returns valid data

Skips gracefully if the MCP package isn't installed or the api container
isn't reachable.
"""
from __future__ import annotations

import asyncio

import pytest


MCP_URL = "http://localhost:8000/mcp"


@pytest.mark.asyncio
async def test_mcp_tools_list():
    try:
        from mcp import ClientSession
        from mcp.client.streamable_http import streamablehttp_client
    except ImportError:
        pytest.skip("mcp package not installed")

    try:
        async with streamable_http_client(MCP_URL) as (read, write, _):
            async with ClientSession(read, write) as session:
                await session.initialize()
                tools = await session.list_tools()
                names = sorted(t.name for t in tools.tools)
                # We expect at least the high-level read endpoints
                expected = {
                    "healthz_healthz_get",
                    "symbols_symbols_get",
                    "features_list_features_list_get",
                    "features_latest_features_latest_get",
                    "paper_trade_summary_paper_trade_summary_get",
                }
                missing = expected - set(names)
                assert not missing, f"MCP tools missing: {missing}"
                # Sanity: many tools registered
                assert len(names) >= 15, f"too few tools registered: {len(names)}"
    except Exception as e:
        pytest.skip(f"MCP server not reachable: {e}")


@pytest.mark.asyncio
async def test_mcp_tools_call_features_list():
    try:
        from mcp import ClientSession
        from mcp.client.streamable_http import streamablehttp_client
    except ImportError:
        pytest.skip("mcp package not installed")

    try:
        async with streamable_http_client(MCP_URL) as (read, write, _):
            async with ClientSession(read, write) as session:
                await session.initialize()
                # The tool name auto-generated by fastapi-mcp encodes the
                # path + method; resolve via list_tools first.
                tools = await session.list_tools()
                feature_tool = next(
                    (t for t in tools.tools if "features_list" in t.name), None
                )
                assert feature_tool is not None, "features_list tool not found"
                result = await session.call_tool(feature_tool.name, arguments={})
                # The result content is a list of TextContent blocks
                content = result.content
                assert content, "features_list returned empty content"
                # Should mention our 6 factors
                text = "\n".join(getattr(c, "text", "") for c in content)
                for f in ("momentum_20d", "rsi_14", "volatility_20d"):
                    assert f in text, f"missing factor {f} in response"
    except Exception as e:
        pytest.skip(f"MCP server not reachable: {e}")